id: P007048
initial_creation_type: ocr
source_metadata:
  id: bdr:W22030
  title: ཤན་འདན་ནང་འཁྲུག་།
  author: ''
  volumes:
    696a285ba940425c87b3d0d858673b61:
      image_group_id: I1KG17142
      title: ''
      volume_number: 1
      total_pages: 170
ebook_metadata:
  title: ཤན་འདན་ནང་འཁྲུག་།
  author: ''
  sku: P007048
  cover: cover.jpg
  layers:
  - pagination
